FROM node:18

WORKDIR /app

RUN rm -rf node_modules package-lock.json

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install --include=dev

ENV PATH /app/node_modules/.bin:$PATH

COPY frontend/ .

CMD ["npm", "start"]